# Generated by Django 5.2.5 on 2025-08-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_rename_details_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
