# Generated by Django 5.2.5 on 2025-08-23 10:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_slot_alter_appointment_status_appointment_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date')},
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.TimeField(),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
