# Generated by Django 5.2.5 on 2025-08-23 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_datetime']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='original_date',
            new_name='appointment_datetime',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'appointment_datetime')},
        ),
        migrations.AddField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='slots',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_rescheduled',
        ),
    ]
