# Generated by Django 5.2.5 on 2025-08-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_options_and_more'),
        ('appointments', '000X_add_is_rescheduled'),
    ]

    operations = [
    ]
